from pathlib import PurePath

SERVER_URL = 'XXX'
WEB_URL = 'XXX'
AUTH0_DOMAIN = 'XXX'
DATA_PATH = PurePath('/xxx/xxx/data')
SENTRY_DSN = 'XXX'
FLOAT_PROJECT_TOKEN = 'XXXX'
SAMPLES_PROJECT_TOKEN = 'XXX'
LABML_VERSION = 'XXX'
IS_MIX_PANEL = True
IS_LOCAL_SETUP = False
